id = "esp32-c3-devkitm-1"
family = "esp32-c3"
arch = "rv32imc"

[memory]
ram_base = "0x3fc80000"
ram_size = "0x00060000"

[gpio]
pins = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

[aliases]
led = 8

[mmio.gpio]
kind = "generic-gpio"
base = "0x60004000"

[mmio.uart0]
kind = "generic-uart"
base = "0x60000000"
